package com.rockville.wariddn.provgwv2.enums;

public enum VnStatus {

    AVAILABLE_NORMAL,
    ACTIVE,
    LOW_BALANCE,
    POWERED_OFF,
    UN_SUBSCRIBED,
    BLOCKED_BY_OPERATOR,
    RESERVED_FOR_OPT_IN,
    RESERVATION_CONFIRMED_AWAITING_CHARGING_RESPONSE,
    AVAILABLE_SILVER,
    AVAILABLE_GOLDEN,
    AVAILABLE_PLATINUM,
    AVAILABLE_DIAMOND,
    ;
}
